### ISSUE TITLE
Carbon X: Create experimental components in React

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-components-react#1512]
The following components have updated html for experimental and need to get updated in the React library. 

- [x] ~~Accordion~~ no markup changes
- [x] ~~Breadcrumb~~ no markup changes
- [x] Buttons https://github.com/IBM/carbon-components-react/pull/1669
- [x] ~~Checkbox~~ no markup changes
- [x] CodeSnippet https://github.com/IBM/carbon-components-react/pull/1675
- [x] ComboBox https://github.com/IBM/carbon-components-react/pull/1713
- [x] ComposedModal https://github.com/IBM/carbon-components-react/pull/1667
- [x] ContentSwitcher https://github.com/IBM/carbon-components-react/pull/1716
- [x] CopyButton https://github.com/IBM/carbon-components-react/pull/1674
- [ ] DataTable (vanilla still in progress https://github.com/IBM/carbon-components/pull/1642)
- [x] ~~DatePicker~~ no markup changes
- [x] ~~Dropdown~~ deprecated
- [x] ~~DropdownV2~~ no markup changes
- [x] FileUploader https://github.com/IBM/carbon-components-react/pull/1645
- [x] ~~Footer~~ no markup changes
- [x] Form
- [x] FormItem
- [x] ~~FormLabel~~ no markup changes
- [x] Icon #1837 #1750
- [x] InlineLoading https://github.com/IBM/carbon-components-react/pull/1642 https://github.com/IBM/carbon-components-react/pull/1762
- [x] ~~Link~~ no markup changes
- [x] Loading https://github.com/IBM/carbon-components-react/pull/1642 https://github.com/IBM/carbon-components-react/pull/1762
- [x] Modal https://github.com/IBM/carbon-components-react/pull/1667
- [x] ~~ModalWrapper~~ no markup changes
- [x] ~~MultiSelect~~ no markup changes
- [x] Notifications https://github.com/IBM/carbon-components-react/pull/1537
- [x] NumberInput https://github.com/IBM/carbon-components-react/pull/1654
- [x] OverflowMenu https://github.com/IBM/carbon-components-react/pull/1767
- [x] OrderedList https://github.com/IBM/carbon-components-react/pull/1723
- [x] Pagination https://github.com/IBM/carbon-components-react/pull/1800
- [x] Progress Indicator https://github.com/IBM/carbon-components-react/pull/1726
- [x] ~~RadioButton~~ no markup changes
- [x] ~~RadioButtonGroup~~ no markup changes
- [x] Search https://github.com/IBM/carbon-components-react/pull/1732
- [x] Select https://github.com/IBM/carbon-components-react/pull/1678
- [x] Slider https://github.com/IBM/carbon-components-react/pull/1683
- [x] StructuredList https://github.com/IBM/carbon-components-react/pull/1528
- [x] ~~Table~~ deprecated
- [x] Tabs https://github.com/IBM/carbon-components-react/pull/1744
- [x] Tag https://github.com/IBM/carbon-components-react/pull/1523
- [x] ~~TextArea~~ no markup changes
- [x] TextInput https://github.com/IBM/carbon-components-react/pull/1687
- [x] Tile https://github.com/IBM/carbon-components-react/pull/1691
- [x] TimePicker https://github.com/IBM/carbon-components-react/pull/1747
- [x] Toggle https://github.com/IBM/carbon-components-react/pull/1693
- [x] ToggleSmall https://github.com/IBM/carbon-components-react/pull/1693
- [x] ~~Toolbar~~ no markup changes
- [x] Tooltip https://github.com/IBM/carbon-components-react/pull/1709
- [x] ~~TooltipDefinition~~ no markup changes
- [x] ~~TooltipIcon~~ no markup changes
- [x] ~~TooltipSimple~~ deprecated
- [x] ~~UnorderedList~~ no markup changes

**Comment by emyarod** [comment]
Tag: https://github.com/IBM/carbon-components-react/pull/1523
StructuredList: https://github.com/IBM/carbon-components-react/pull/1528
Notification: https://github.com/IBM/carbon-components-react/pull/1537
