### ISSUE TITLE
Slider component revamp

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/carbon-components-react#330]
## Overview

The `Slider` component is pretty buggy and should be revisited to make sure it's working as intended.

- [x] Make sure min < 0 works as intended https://github.com/carbon-design-system/carbon-components-react/issues/233
- [x] Switch to NumberInput so it only accepts numbers
- [x] Make sure the labels are easily customizable
- [x] https://github.com/carbon-design-system/carbon-components-react/issues/287 **Slider - Text input does not work properly when ranges are used**
- [x] https://github.com/carbon-design-system/carbon-components-react/issues/278 **Slider input field accepts letters and numbers..for usage we only want input field to accept numbers**

Related issues:

https://github.com/carbon-design-system/carbon-components-react/issues/234 **Slider min/max value labels can be formatted externally**
https://github.com/carbon-design-system/carbon-components-react/issues/329 **Slider onChange not working with setState**
